### ISSUE TITLE
zipFile.BadZipFile: File is not a zip file Error?

### ISSUE THREAD

**Issue by DeckardKane** [SeriousBug/redditcurl#1]
Hello! I'll get this out of the way first: I'm a Linux scrub, so in all likelihood I have something configured wrong. I'm running redditcurl on ubuntu 14.04, I've gotten all the requirements installed with pip, etc.
 [However...this is what I get when I try running redditcurl.](http://pastebin.com/ezLwn9f1)
Again, it's more than likely that I just did something stupid when setting this up :(

**Comment by SeriousBug** [comment]
Thanks for bringing this up, the problem certainly isn't your mistake. I added a check for that error and released a new version, could you update and run the program again? That should no longer cause a crash.

I also added some error logging for that part, so you should see something like "Error while downloading http://example.com/my-image : File is not a zip file". If you could give that line, that would be helpful, because it seems that there is a further problem in the downloader for imgur albums.

**Comment by DeckardKane** [comment]
Well, I ran into a different problem. I tried cloning as opposed to grabbing the package off the Python Package Index, and running setup.py gives me a syntax error. I'm assuming it's the character at the end of your name :( Specifically: SyntaxError: Non-ASCII character '\xc3' in file setup.py on line 9, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details
It's a simple comment at the top of the file to fix (`# -*- coding: utf-8 -*-` or something like that), according to the PEP anyway, and I would have just pushed it but I don't have access (which is okay, I don't want to butt in on your project :) ). Regardless, I realized that the Python Package Index version had been updated as well, and got everything working that way.

But regarding this error: I now get three seemingly unrelated errors, but the good news is that it doesn't completely kill the program anymore. It looks like the File is not a zip file error is coming through okay, this is what it looks like: Error while downloading http://imgur.com/a/XhFlY : File is not a zip file. I don't get any more detail than that, unfortunately :( 

I also saved a massive (over 1000 images) imgur album to see what would happen. This is the error I got when it tried to download that album: Error while downloading http://imgur.com/a/odVXZ : Failed downloading imgur album http://imgur.com/a/odVXZ. I'm assuming this one is because when imgur albums get too big, you don't get a zip file right away, they email you when it's ready. I'm not sure what can be done about that.

And finally, a weird protocol error that may be a problem with permissions on my Virtualbox, but I'll list it anyway: Error while downloading http://i.imgur.com/pANydBi.jpg : [Errno 71] Protocol error: '/home/peter/Desktop/sf_Ubuntu_Downloads/redditImagesTest/The Reflection of white trees in water[3840*2160].jpeg'

Sorry for the delay (and the block of text), I hope this is helpful!

**Comment by SeriousBug** [comment]
>  I tried cloning as opposed to grabbing the package off the Python Package Index, and running setup.py gives me a syntax error.

That is because Ubuntu still uses python2 as default, while redditcurl only supports python3. It should work if you install it like `python3 setup.py install`.

> this is what it looks like: Error while downloading http://imgur.com/a/XhFlY : File is not a zip file. ... I'm assuming this one is because when imgur albums get too big, you don't get a zip file right away, they email you when it's ready.

That seems to be the case. Normally, imgur serves the zip file when you add zip to the end of the url, like `http://imgur.com/a/XhFlY/zip`. However for these big albums it just redirects back to the album page.

> And finally, a weird protocol error that may be a problem with permissions on my Virtualbox, but I'll list it anyway

This one works on my end. I dug up a bit on the error, it seems to be [EPROTO](http://linux.die.net/man/3/errno) POSIX error. I couldn't find a description of what the error actually is, but I came across [another person having the same problem on a VM](https://stackoverflow.com/questions/31756495/ioerror-errno-71-protocol-error-when-reading-a-file-with-python-in-a-virtua), so I'm willing to bet it is a problem with the VM.

**Comment by DeckardKane** [comment]
I guess that's what happens when I try to do things on very little sleep, I did not realize I was attempting to use python2, whoops! Everything else seems to be working just fine! Thanks so much, this is a really nice utility :)
